spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kyc_database?escapeSyntaxCallMode=callIfNoReturn&reWriteBatchedInserts=true
    username: kyc_user
    password: kyc_pass
    hikari:
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        generate_statistics: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


server:
  port: 9002

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE