spring:
  application:
    name: kyc-campaigns
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    external-services:
      enabled: true
  info:
    build:
      enabled: false

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-CAMPAIGNS-001
        message: Unexpected Error
        type: ERROR
      "002":
        code: KYC-CAMPAIGNS-002
        message: The element was not found
        type: WARN
      "003":
        code: KYC-CAMPAIGNS-003
        message: The catalog was not found
        type: WARN